upgrade next-translate
quran/quran.com-frontend-next pull request #191
Opened 2021-07-12 12:09 UTC by osamasayed

### Summary
Upgrate next-translate package to version `1.0.7`.

### Test Plan

### Screenshots

| Before | After |
| ------ | ------ |
| [image here] | [image here] |

2021-07-12 17:32 UTC, tifa2UP requested changes
Looks good masha'Allah. Another part that needs change is migrating the `next-translate/Link` to `next/link`

Afterwards the PR is good to go insha'Allah

2021-07-12 17:32 UTC, tifa2UP commented on i18n.json
> +}
nit: new line

2021-07-12 17:32 UTC, tifa2UP commented on package.json
> +}
nit: new line

2021-07-13 00:14 UTC, osamasayed commented
> Looks good masha'Allah. Another part that needs change is migrating the `next-translate/Link` to `next/link`
> 
> Afterwards the PR is good to go insha'Allah

This has already been changed in this PR: https://github.com/quran/quran.com-frontend-next/pull/186/commits/5772491522ca313f052918e4ae9dcbfd49aa4c3e#diff-30469af39e44cfa66c6d1d643f6e1b6520d4d057b6856a43e36fbb3e98e70ea4

2021-07-13 00:19 UTC, osamasayed commented on i18n.json
> +}
Done

2021-07-13 00:19 UTC, osamasayed commented on package.json
> +}
Done

2021-07-14 07:42 UTC, tifa2UP approved these changes

2021-07-14 07:42 UTC, merged