UI Improvements: Modernized Scrollbars and Dark Mode Bug Fix
quran/quran.com-frontend-next pull request #1963
Opened 2023-05-01 18:43 UTC by Tajmirul

### Summary

- More modern and user-friendly scrollbars.
- In dark mode, there was a bug in the banner on the home page. `data-theme` was hard-coded to `light`, as a result, the search box was white in dark mode. Now it's also dynamic, coming from the Redux store.

By implementing these changes, we hope to make our software project more accessible and enjoyable to use for all users. We appreciate your time and consideration in reviewing this pull request and welcome any feedback you may have.

### Screenshots

| Before | After |
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/62275307/235506203-dc7aeae0-5122-4ee4-bbb3-7b10d3b55843.png) | ![image](https://user-images.githubusercontent.com/62275307/235506326-22b68690-630e-4b12-9123-7ae0911e7c4c.png) |
| ![image](https://user-images.githubusercontent.com/62275307/235506497-4663c66c-987f-4426-ada4-a0be188ba4e9.png) | ![image](https://user-images.githubusercontent.com/62275307/235506597-68f4ba26-3c71-405e-ac8d-c100ac93f546.png) |

2023-06-11 18:28 UTC, ahmedriad1 requested changes
Salam alykum @Tajmirul,

JAK for your amazing contribution!

PR looks amazing masha'Allah, just left a couple of comments.

2023-06-11 18:28 UTC, ahmedriad1 commented on src/components/HomePage/HomePageHero.tsx
Please revert the changes in this file. The hero section was intentionally made to look like this.

2023-06-11 18:28 UTC, ahmedriad1 commented on src/components/HomePage/HomePageHero.module.scss
Please revert the changes in this file. The hero section was intentionally made to look like this.

2023-06-12 10:14 UTC, Tajmirul reviewed
the hero section is in the previous style

2023-06-12 10:14 UTC, Tajmirul commented on src/components/HomePage/HomePageHero.module.scss
Resolved

2023-06-12 11:07 UTC, osamasayed approved these changes

2023-06-12 11:08 UTC, merged

2023-06-12 11:09 UTC, osamasayed commented
Jazak Allahu Khairan @Tajmirul for your contribution. PR will be included in the upcoming release inshAllah.

2023-06-12 11:25 UTC, Tajmirul commented
Wa antum fa-jazakumullahu khayran @osamasayed. I am happy to contribute to the project and I am glad that my PR will be included in the upcoming release. I look forward to seeing the project grow and succeed.

2025-05-02 12:58 UTC, Amandeep-Chauhan commented
jai shree raaaaaam

2025-05-02 12:58 UTC, Amandeep-Chauhan commented
modi modi modi