Add notes
quran/quran.com-frontend-next pull request #2044
Opened 2023-11-21 11:01 UTC by osamasayed

2023-11-22 10:05 UTC, osamasayed commented on types/NoteType.ts
> +  AyahsRange = 'ayahsRange',
let's remove this.

2023-11-22 10:07 UTC, osamasayed commented on types/auth/NotesByTypeAndTypeIdResponse.ts
> +  updatedAt: Date;
We should add `ranges` field here

2023-11-22 10:13 UTC, osamasayed commented on src/components/QuranReader/TranslationView/TranslationViewVerse/TranslationPageVerse.tsx
> +  const { data: notesCount } = useSWR(
Why cannot we just use `useSWRImmutable`?

> `useSWR(key, fetcher, { revalidateIfStale: false, revalidateOnFocus: false, revalidateOnReconnect: false })` is equivalent to `useSWRImmutable(key, fetcher)`

2023-11-23 03:27 UTC, osamasayed commented on src/utils/auth/api.ts
> +  // // }
we should remove this

2023-11-23 03:27 UTC, osamasayed commented on src/utils/auth/api.ts
> +    // ...attachedEntityPayload,
ditto: we should remove this

2023-11-23 04:47 UTC, osamasayed commented on src/components/Verse/Notes/index.tsx
> +    logButtonClick('verse_actions_menu_note', {
nit: the trigger type should be included here

2023-11-26 04:57 UTC, ahmedriad1 requested changes

2023-11-26 04:57 UTC, ahmedriad1 commented on src/components/Notes/NoteModal/utils/ranges.ts
Remove this util, we already have `parseVerseRange`

2023-11-26 04:57 UTC, ahmedriad1 commented on src/components/Notes/NoteModal/NoteRangesIndicator/index.tsx
> +  )}`;
Remove this code and do this:
```ts
const [
  { chapter: fromChapter, verse: fromVerse, verseKey: rangeFrom },
] = parseVerseRange(range);
const verseKeyName = `${getChapterData(chaptersData, fromChapter).transliteratedName} ${toLocalizedNumber(Number(fromVerse), lang)}`;
```

2023-11-26 07:27 UTC, merged