Fixed developer utility UI and made some tweaks to the chapter Arabic names and Navigation drawer.
quran/quran.com-frontend-next pull request #230
Opened 2021-08-09 02:53 UTC by microart-inc

### Summary
Reworked developer utility UI to better match the rest of the app. Also vertically centered the Arabic surah names on the right-hand side on the main page. Some links in the navigation sidebar were also not highlighting on hover, so those were fixed as well.

### Test Plan
The developer utility looks much cleaner and still retains the same functionality. The navigation drawer links highlight the primary blue color on hover, and the Arabic surah names are centered vertically.

### Screenshots

| Before | After |
| ------ | ------ |
| https://imgur.com/a/kXJHDqn | https://imgur.com/a/PIKPVOo |

2021-08-09 07:12 UTC, tifa2UP requested changes

2021-08-09 07:12 UTC, tifa2UP commented on src/components/DeveloperUtility/DeveloperUtility.module.scss
> +	background: rgb(230, 230, 230);
Thank you microArt for your PR! Love the new functionality.

We avoid using hardcoded values for colors, sizing etc. Please check the theme.scss file and see which variable most closely aligns with your desired UI. 

It applies for all the custom values in this PR.

2021-08-10 05:10 UTC, microart-inc reviewed
Moved all sizing and colors from hardcoded values to variables provided in theme.scss.

2021-08-10 05:20 UTC, tifa2UP commented
Thank you, this looks great. Can you pull master and resolve the merge conflicts? Good to go afterwards insha'allah

2021-08-10 06:10 UTC, microart-inc commented
Fixed merge conflicts with 'master'

2021-08-10 07:38 UTC, tifa2UP commented
Can you pull the latest master once more? I see a few conflicting files. Also feel free to ping me on our discord: https://discord.gg/PJ435cSk

src/components/DeveloperUtility/DeveloperUtility.module.scss
src/components/Navbar/NavigationDrawer/NavigationDrawerItem.module.scss
src/components/chapters/ChapterBlock.module.scss
src/styles/theme.scss

2021-08-10 17:56 UTC, merged

2021-08-10 17:56 UTC, tifa2UP commented
Merged! Thank you microart